package com.example.pruebajuego.dataStore

import kotlinx.serialization.Serializable

@Serializable
data class PoopData(
    val cacasTotales: Float = 0f,
    val cacasClick: Double = 1e0,
    val diamantesTotales: Double = 1e0,
    val cantidadCacaTotales: Int = 0,
    val cantidadaAcumuladaCacas: Double = 0e0,
    val cantidadSumar: Float = 0f,
    val autoSumar: Boolean = false,
    val precioYourBath: Int = 20,
    val precioSumClick: Int = 30,
    val precioInodoros: Int = 1000,
    val precioPopClicker: Double = 5e3,
    val precioPublicBath: Double = 2e4,
    val precioVertedero: Double = 1e5,
    val precioPopClicker2: Double = 5e5,
    val precioAnimals: Double = 2e6,
    val precioBestPopClicker: Double = 5e6,
    val precioBestPooper: Double = 1e7,
    val precioPoopCities: Double = 5e7,
    val precioMultiPoops: Double = 1e8,
    val precioSmartPoop: Double = 6e8,
    val precioPoopEconomy: Double = 3e9,
    val precioFireFinguer: Double = 4e10,
    val precioAncientPoops: Double = 1e11,
    val precioPoopEarht: Double = 5e12,
    val precioPoopStars: Double = 1e13,
    val precioToolsClick: Double = 7e14,
    val precioCleanPoops: Double = 1e16,
    val precioAscendPoops: Double = 5e18,
    val precioPoopAge: Double = 1e20,
    val precioCliker: Double = 1e22,
    val mostrarClickUpgrade: Boolean = false,
    val mostrarClickUpgrade2: Boolean = false,
    val mostrarClickUpgrade3: Boolean = false,
    val mostrarClickUpgrade4: Boolean = false,
    val mostrarClickUpgrade5: Boolean = false,
    val mostrarClickUpgrade6: Boolean = false,
    val mostrarClickUpgrade7: Boolean = false,
    val mostrarClickUpgrade8: Boolean = false,
    val mostrarClickUpgrade9: Boolean = false,
    val mostrarClickUpgrade10: Boolean = false,
    val mostrarClickUpgrade11: Boolean = false,
    val mostrarClickUpgrade12: Boolean = false,
    val mostrarClickUpgrade13: Boolean = false,
    val mostrarClickUpgrade14: Boolean = false,
    val mostrarClickUpgrade15: Boolean = false,
    val mostrarClickUpgrade16: Boolean = false,
    val mostrarClickUpgrade17: Boolean = false,
    val mostrarClickUpgrade18: Boolean = false,
    val mostrarClickUpgrade19: Boolean = false,
    val mostrarClickUpgrade20: Boolean = false,
    val mostrarClickUpgrade21: Boolean = false,
    val mostrarClickUpgrade22: Boolean = false,
    val mostrarClickUpgrade23: Boolean = false,
    val mostrarClickUpgrade24: Boolean = false,
)